version: "3.9"

networks:
  spoke-components:
    external: true
  default:
    external:
      name: spoke-components

services:
  web:
    build: app/
    environment:
      APP_ENV_IA: "${APP_ENV_IA}"
      AWS_REGION: "${AWS_REGION}"
      AWS_SHARED_CREDENTIALS_FILE: '/.aws/credentials'
      NEO4J_SPOKE_HOSTNAME: "${NEO4J_SPOKE_HOSTNAME}"
      NEO4J_SPOKE_PASS: "${NEO4J_SPOKE_PASS}"
      NEO4J_SECRETS_NAME: "${NEO4J_SECRETS_NAME}"
      NEO4J_SPOKE_USER: "${NEO4J_SPOKE_USER}"
      PSEV_API_KEY: "${PSEV_API_KEY}"
      PSEV_SECRETS_NAME: "${PSEV_SECRETS_NAME}"
      PSEV_SERVICE_HOSTNAME: "${PSEV_SERVICE_HOSTNAME}"

    networks:
      spoke-components:
        aliases:
          - improving-agent
    ports:
      - "3031:3031"
      - "3032:3032"
    volumes:
      - ./app:/usr/src/app
      - ~/.aws:/.aws